name: Remaster Version Game Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remaster
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make all
      run: make all
    - name: make clean
      run: make clean
